[tool.poetry]
name = "clickapp"
version = "0.1.0"
description = ""
authors = ["Tarun Jethwani"]

[tool.poetry.dependencies]
python = "^3.8"
click = "8.0.1"
attrs = "^19.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
